
trigger:
- master
variables:
 BuildConfiguration: 'Release'
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: windows-latest
        steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.100'
        - task: NuGetToolInstaller@1
          inputs:
            versionSpec: 
        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: '**/*.sln'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/*.sln'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.sln'
            arguments: '--no-restore --configuration release'